FROM golang:alpine

WORKDIR /app
EXPOSE 8080

COPY ./cmd/Producer/main.go .
COPY ./pkg ./pkg
COPY go.sum .
COPY go.mod .

RUN go mod download

RUN go build -o main main.go
RUN chmod +x main
CMD ["./main"]
